---
- hosts: templatevm
  vars_files:
    - ./vars/db001.yml
  become: yes
  tasks:
      - name: set hostname
        hostname:
          name: "{{ newhostname }}"

      - name: set ipaddress
        command: nmcli connection modify "{{ newnic }}" ipv4.method manual ipv4.addresses "{{ newipaddress }}"/24 

      - name: shutdown
        command: shutdown -h now

...
